/*
	insert into table productSupplier the primary key for each product and supplier based on table.column product.id and supplier.id
	
	data provided in format (<product.description>, <supplier.supplierName>)	
*/

(<lamb shank in rosemary and mint sauce>, <New Direction Foods>)
(<veal osso buco>, <New Direction Foods>)
(<braveheart angus beef boneless short rib>, <New Direction Foods>)
(<braveheart angus beef flank steak>, <Monogram Foods>)
(<boneless chicken breasts >, <Monogram Foods>)
(<bacon-wrapped pork chops>, <Monogram Foods>)
(<medium wild langoustines>, <Dutt and Wagner of Virginia, Inc>)
(<cooked small octopus tentacles>, <Dutt and Wagner of Virginia, Inc>)
(<red shrimp from argentina XL>, <Dutt and Wagner of Virginia, Inc>)
(<coquina clams>, <Culinary Specialties, Inc>)
(<extra fine french peas >, <Culinary Specialties, Inc>)
(<artichoke bottoms>, <Culinary Specialties, Inc>)
(<very find yellow wax beans>, <John E. Koerner Company>)
(<broccoli florets>, <John E. Koerner Company>)
(<family size smashed red potatoes>, <John E. Koerner Company>)
(<family size whipped sweet potatoes>, <Diversified Foods and Seasonings LLC>)
(<potatoes au gratin>, <Diversified Foods and Seasonings LLC>)
(<jasmine rice>, <Diversified Foods and Seasonings LLC>)
(<brown, red and wild rice medley>, <Ajinomoto Foods North America>)
(<organic quinoa>, <Ajinomoto Foods North America>)
(<black beluga lentils>, <Ajinomoto Foods North America>)
(<frangipane king cake>, <Ascot Valley Foods>)
(<chocolate croissant>, <Ascot Valley Foods>)
(<tiramisu classico>, <Ascot Valley Foods>)
(<authentic french creme brulee>, <Kellogg NA Company>)
(<cappuccino pie>, <Kellogg NA Company>)
(<red berry cheesecake>, <Kellogg NA Company>)
(<brioche burger buns>, <AppetizersUSA>)
(<ciabatta sandwich 6 inch >, <AppetizersUSA>)
(<mini blinis>, <AppetizersUSA>)